version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./myproject:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
